### ISSUE TITLE
safari landing page header missing. 

### ISSUE THREAD

**Issue by brucefeynman** [Pallet-io/pallet.io#3]
header is missing on the landing page, appears after scrolling down.
<img width="1243" alt="screen shot 2018-02-02 at 2 56 00 pm" src="https://user-images.githubusercontent.com/20383674/35720609-69680ffe-0829-11e8-8307-b30f10dbec95.png">

**Comment by DeemoHarlos** [comment]
I don't have Safari browser at hand. Could you specify device type and the console error (if there is any)?

**Comment by DeemoHarlos** [comment]
Fixed. Merged to master.
