### ISSUE TITLE
More friendly and concise adaptive design

### ISSUE THREAD

**Issue by magrady24** [Pallet-io/pallet.io#4]
The current mobile version is built by the CSS with a special selector, sets by mobile.css to override the original style

**Comment by brucefeynman** [comment]
you can choose different css file based on the pixel of the browser

**Comment by magrady24** [comment]
Too many duplicate parts can cause maintenance inconvenience, so there are still major CSS and other files as special adjustments by some browser and the orientations.

**Comment by DeemoHarlos** [comment]
RWD will be on process soon after, no worries.

**Comment by DeemoHarlos** [comment]
In progress

**Comment by DeemoHarlos** [comment]
@magrady24 RWDs just work this way.
Most attributes in index.css are common. Those in mobile.css are just modification. 
So it makes more sense to see like that.

RWD is done by now. Open another issue if any problem is found.
