### ISSUE TITLE
chrome header missing

### ISSUE THREAD

**Issue by brucefeynman** [Pallet-io/pallet.io#7]
chrome header is missing all the time.
<img width="980" alt="screen shot 2018-02-02 at 3 04 41 pm" src="https://user-images.githubusercontent.com/20383674/35720879-8868c7a8-082a-11e8-8e15-fdf0882f62ff.png">

**Comment by DeemoHarlos** [comment]
Please specify your device type, thanks. 
It's all working fine on Chrome, Ubuntu 16.04

**Comment by DeemoHarlos** [comment]
Closed for now. If any problem remains, reopen this issue.

**Comment by zhouer** [comment]
Same issue, but nav bar shows when pointer moves to top of screen (where the nav bar should be)
Windows 10, Chrome 63

**Comment by DeemoHarlos** [comment]
That's a feature asked by @magrady24 and @Tony-HSU .
The nav bar shows whenever it is hovered, or scrollTop is larger than 400.

**Comment by zhouer** [comment]
Thanks!
